class DatabaseImpl:
    def __init__(self):
        ...

    def createCollection(self, name):
        ...

    def listCollections(self):
        ...

    def collection(self, name):
        ...

    def deleteCollection(self, name):
        ...

    def queryCollections(self, opts=None):
        ...
